# For puppetlabs_spec_helper documentation - see http://github.com/puppetlabs/puppetlabs_spec_helper

fixtures:
  repositories:
    apache: 'https://github.com/puppetlabs/puppetlabs-apache.git'
    concat: 'https://github.com/puppetlabs/puppetlabs-concat.git'
    mysql:  'https://github.com/puppetlabs/puppetlabs-mysql.git'
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    zabbix: 'https://github.com/dj-wasabi/puppet-zabbix.git'
  symlinks:
    zabbixserver/files: '../../../../files'
    zabbixserver/manifests: '../../../../manifests'
    zabbixserver/templates: '../../../../templates'
